/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Assignement_4;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

import com.Teacher;
import com.Student;
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String[] args) {
		EntityManagerFactory emf = Persistence.createEntityManagerFactory("TeacherPU");
		EntityManager entityManager = emf.createEntityManager();
		Teacher teach = new Teacher();
		teach.setTeacherId(1);
		teach.setTeacherName("sailesh");
		teach.setSubject("Persistence");
		
		List<Student> mylist = new ArrayList<Student>();
		mylist.add(new Student("Indu", "8th semester", teach));
		mylist.add(new Student("Priya", "7th semester", teach));
		mylist.add(new Student("siddartha", "7th semester", teach));
		mylist.add(new Student("Suresh", "6nd semester", teach));
		teach.setList(mylist);
		
		entityManager.getTransaction().begin();
		entityManager.persist(teach);
		entityManager.flush();
		entityManager.getTransaction().commit();
	}
}